# Dependencies
markdown:         redcarpet
highlighter:      rouge

gems: [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Coderashed
tagline:          'Coderashed'
description:      'Learning my lesson one rash at a time.'
url:              http://coderashed.github.io
baseurl:          /

author:
  name:           'Steven Shurtliff'
  url:            https://twitter.com/coderash

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/coderashed
