# Dependencies
markdown:         redcarpet
highlighter:      pygments

gems: [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Coderashed
tagline:          'Coderashed'
description:      'Learning my lesson one rash at a time.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
